---
ID: "94d2576d-b69b-4796-acee-5198bc6011cb"
Parent: "b8ed3feb-0dce-4ec7-b413-11d373b9925a"
Template: "b8ed3feb-0dce-4ec7-b413-11d373b9925a"
Path: /sitecore/templates/Project/Workwear/Page Content/Slider Carousel Component/Slider Carousel Component/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{B5946979-CC6E-4101-80D4-757590708E13}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "72f9bad5-2ad7-44e6-9748-d0b7720dbc3a"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260120T125157Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9e776a5f-0088-44c4-9879-5dc7c5ac0770"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260120T130329Z
