---
ID: "c61bc81f-c271-43f0-89f0-0c179ba3172d"
Parent: "7a33238e-5d05-4550-9101-17dbf1ea4e6f"
Template: "7a33238e-5d05-4550-9101-17dbf1ea4e6f"
Path: /sitecore/templates/Project/Workwear/Page Content/Find Your Product/Find Your Product/__Standard Values
SharedFields:
- ID: "33ef3947-9acd-41b7-8d85-413e515e64c4"
  Hint: EntityName
  Value: content
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260218T150100Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\manoj@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\manoj@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5b9c6939-6999-499b-bea3-e54748625770"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260218T150201Z
