---
ID: "47147aa7-4cde-41a4-a1bd-0eb030c16a88"
Parent: "5dca956d-6d5e-4bb6-a62b-f2c38f7c0fc4"
Template: "5dca956d-6d5e-4bb6-a62b-f2c38f7c0fc4"
Path: /sitecore/templates/Project/Workwear/Base/Footer/Global Footer/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251201T210326Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "527cb7d9-c194-42bd-9366-42483249c08a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251201T210326Z
