---
ID: "03a5be22-46f3-4144-b7ba-e4443e68c766"
Parent: "9c53405a-e5c0-48b5-875c-a8e2d9546135"
Template: "9c53405a-e5c0-48b5-875c-a8e2d9546135"
Path: /sitecore/templates/Project/Workwear/Page Content/Testimonial/Testimonial/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251204T105419Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e7dca66a-b5fd-47d7-9c04-4e5604b760a8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251204T105419Z
