---
ID: "d2c7c204-52ec-4698-9c37-1f55bbdddf04"
Parent: "d37747b8-11f3-4d87-a48e-d9f84e5d0850"
Template: "d37747b8-11f3-4d87-a48e-d9f84e5d0850"
Path: /sitecore/templates/Project/Workwear/Page Content/Product Teaser Grid/Product Teaser Item/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251201T162601Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c6068b59-9958-43c2-8f73-2a8c6b100797"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251203T220324Z
