---
ID: "54d1ab61-91cf-4c6d-9540-5c3e2eb5a635"
Parent: "5cf06b2f-ed7c-452c-9933-f181061c2f3c"
Template: "5cf06b2f-ed7c-452c-9933-f181061c2f3c"
Path: /sitecore/templates/Project/cws/Page Content/Website Box/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260215T140928Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "beb4cca9-3ad7-4b68-a4e9-fdfa32fbbced"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260215T140928Z
