---
ID: "6249d325-1487-4a4c-82d8-ddcd10266344"
Parent: "bd964fce-383a-4616-a732-15d063ac3432"
Template: "bd964fce-383a-4616-a732-15d063ac3432"
Path: /sitecore/templates/Project/Workwear/Page Content/Landing Pages/Landing Page Product Collections/Product Collection Tabs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{CC26F343-E5E6-4F9C-BD1B-5A89EBEE89A0}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c6c5f6d9-b5dc-41bd-9a76-09d93aa45385"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260303T164936Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4a4688c4-84c0-40e0-9967-0a5e237e504b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260303T165334Z
