---
ID: "8d5fc0f1-b162-4181-933a-5f585f124fcc"
Parent: "7f50c9f9-d96c-4bd8-aa29-946d5ab0edba"
Template: "7f50c9f9-d96c-4bd8-aa29-946d5ab0edba"
Path: /sitecore/templates/Project/Workwear/Page Content/Certificates Slider/Certificate/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251229T155933Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3edf80ab-3aa7-48ae-815b-7867556d0442"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251229T155933Z
