---
ID: "4dfe9710-82be-423f-bb62-4831c83b6570"
Parent: "92b1ed02-dda9-4f4e-82a1-2ac816164970"
Template: "92b1ed02-dda9-4f4e-82a1-2ac816164970"
Path: /sitecore/templates/Project/Workwear/Page Content/Find Your Job/Find Your Job Data Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{27FA6175-A59D-41E6-A4E6-663000E08D4B}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "0b2777e4-a389-4090-b603-656f65f43e1d"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260224T152140Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\manoj@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\manoj@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ef1ebe6f-baec-43d7-a6d1-ed7310a8261c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260224T152221Z
