---
ID: "9a376011-b804-4fc8-8923-02b707ff6c43"
Parent: "47bb4398-2b9c-466e-99fb-5e51d9dde7d1"
Template: "47bb4398-2b9c-466e-99fb-5e51d9dde7d1"
Path: /sitecore/templates/Project/Workwear/Page Content/Landing Pages/Landing Page Hero/LandingPageHero/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260303T150552Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "891c0d29-64e9-40d4-baf7-8f45e609c7be"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260303T150552Z
