---
ID: "63fbbf94-bad6-4efc-b9ae-6641c0462fb9"
Parent: "21ca50aa-08b3-4940-9a46-ae4c4a311dd8"
Template: "21ca50aa-08b3-4940-9a46-ae4c4a311dd8"
Path: /sitecore/templates/Project/Workwear/Page Content/Landing Page Columns/LandingColumns/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{AA9ABA84-84D4-4492-AFF7-3B0F4D1347CA}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "5a070c86-8310-45a0-b518-254db72efabf"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251225T105335Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3f90dd12-3161-4c7a-a9b2-0330ccb19b02"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251225T105421Z
