---
ID: "772339ef-cea5-41e3-833f-c2936a02b224"
Parent: "6514521a-2bd5-438d-ba97-4b85f1ad3d6c"
Template: "6514521a-2bd5-438d-ba97-4b85f1ad3d6c"
Path: /sitecore/templates/Project/Workwear/Page Content/Areas Component/AreasComponent/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{726033DF-475B-4DB5-8F9E-97E457763FC0}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "aec3bdbb-840c-4b31-8cae-33fff7ed0fa1"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251205T084416Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9c882557-6d32-4f85-b166-1ccd8f073e92"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251224T211406Z
