---
ID: "d6a0be18-8b8e-4519-810c-b2e72d4716e0"
Parent: "4455c67a-7fff-4d05-8fe6-a4d2fae04fb9"
Template: "4455c67a-7fff-4d05-8fe6-a4d2fae04fb9"
Path: /sitecore/templates/Project/Workwear/Base/SEO/_SEO Metadata/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251115T191610Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2015c6ae-5b82-4f41-90fd-6e2f93c023b1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251115T191610Z
