---
ID: "93e2a374-da47-4dae-a275-b9fcdca32bef"
Parent: "2dda7aba-3b37-4ff4-a7ec-67842b13cbe1"
Template: "2dda7aba-3b37-4ff4-a7ec-67842b13cbe1"
Path: /sitecore/templates/Project/Workwear/Base/LinkList/Link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251107T145958Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aafd3712-7d98-46b5-bdc3-d9576aa5877b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251107T145958Z
