---
ID: "a388022c-7276-42dc-86a6-a8d2f8b90a50"
Parent: "871b6559-a8e1-45b7-b7ef-b00ff8b2fd91"
Template: "871b6559-a8e1-45b7-b7ef-b00ff8b2fd91"
Path: /sitecore/templates/Project/Workwear/Page Content/Image Gallery/ImageGalleryItemFolder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{59300D76-233D-4960-893B-AC3E4F52BAD2}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "dc514ee8-e3a0-45d6-939a-18719a029736"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251202T043607Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eff92955-fd56-4591-ac99-ac83585fff02"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251202T043733Z
