---
ID: "40296bcd-84aa-4573-a725-3146d8d1f00a"
Parent: "34c83c4d-3848-465f-b1e7-b87c025db8e1"
Template: "34c83c4d-3848-465f-b1e7-b87c025db8e1"
Path: /sitecore/templates/Project/Healthcare/Headless Tenant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260114T120719Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f61eeba5-1b74-40d2-ba79-44632f46138a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260114T120719Z
