---
ID: "03df9517-d6f3-48b3-b179-c894fd41acf3"
Parent: "64a37e12-4d91-4387-a8ad-18a22e27acf1"
Template: "64a37e12-4d91-4387-a8ad-18a22e27acf1"
Path: /sitecore/templates/Project/Workwear/Page Content/Videos Player/VideoPlayerFolder/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Multimedia/32x32/open_video_h.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C1CCBD5A-D7B4-426C-BB0C-75EA51B8282F}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "7f9cc437-a599-4b93-a382-8f695a7a276f"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251202T132912Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7e3ce497-4207-4ce3-9452-4dc8c94ea0aa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251205T102730Z
