---
ID: "9dc4beea-6a0d-4ef5-ab5c-2970993fbc73"
Parent: "a73f4d00-cfe1-4e53-b9ef-972ca1d3adf4"
Template: "a73f4d00-cfe1-4e53-b9ef-972ca1d3adf4"
Path: /sitecore/templates/Project/Workwear/Page Content/Product Teaser Grid/Product Teaser Grid/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{D37747B8-11F3-4D87-A48E-D9F84E5D0850}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "e8849d1c-8185-4ce6-8021-033c8a3e97bf"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251201T161610Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "887f1c74-4b17-4a89-8ab3-d24f79e07e8d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251203T222102Z
