---
ID: "bbdaffbd-effd-465b-8559-acacb165280a"
Parent: "f47f0611-30b7-42de-b214-a1fb1463b58e"
Template: "f47f0611-30b7-42de-b214-a1fb1463b58e"
Path: /sitecore/templates/Project/Workwear/Page Content/SpotlightStories/Spotlight Stories/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{426DDEB9-A959-411C-91EE-8C38EC73275B}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "be5b4a99-da69-4db7-a2a2-cffe044ae9ea"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251204T095449Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6cb2ec02-6b30-4803-9ad8-3290f5f23cbe"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260122T054953Z
