---
ID: "0871d308-daba-406b-9614-802c3fdc38e7"
Parent: "28a933bd-01df-4d39-b45b-b418b6f6bd61"
Template: "28a933bd-01df-4d39-b45b-b418b6f6bd61"
Path: /sitecore/templates/Project/Workwear/Page Content/Promo/Promo Card Data folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{91D312C1-E2F9-4228-9889-43BEC1FF30DF}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ea9bdc8c-2ab4-4508-9cc8-8f47ae6c779c"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260220T133153Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\manoj@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\manoj@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e0177de9-5d8d-4a48-afe7-03eb79affe66"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260220T133159Z
