---
ID: "71a77fd8-ee01-4f5a-97c4-fb42a4879561"
Parent: "a84ea48c-7bd4-4a20-a289-e3f3f22effd2"
Template: "a84ea48c-7bd4-4a20-a289-e3f3f22effd2"
Path: /sitecore/templates/Project/Workwear/Page Content/Text Highlight/TextHighlight/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: WordProcessing/32x32/align_right.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{A84EA48C-7BD4-4A20-A289-E3F3F22EFFD2}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "1333772f-fd02-4e0d-96f1-eaf0511819cd"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251201T184353Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3214f69d-53e9-478a-bba1-d5c26d356731"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251212T160840Z
