---
ID: "fdd5ece5-317c-4dd0-9de0-1beebdd0bd7d"
Parent: "32100657-f753-47bc-88f3-3bd9362e565f"
Template: "32100657-f753-47bc-88f3-3bd9362e565f"
Path: /sitecore/templates/Project/Workwear/Page Content/Industry Sector Teaser/IndustrySectorTeaser/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251201T081712Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0f1c4354-c3d3-4efb-af12-3ab5999acf4b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251201T081712Z
