---
ID: "916b91c1-1e46-4567-999b-3a38ded30b86"
Parent: "ab9a500e-3470-4ff1-984e-5c12d796daf9"
Template: "ab9a500e-3470-4ff1-984e-5c12d796daf9"
Path: /sitecore/templates/Project/Workwear/Page Content/Client Endorsements/ClientEndorsementsItemFolder/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /~/icon/multimedia/32x32/new_image.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{63554502-D2E2-4A36-AD9E-CEA0B7EDF699}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "36a10411-7cb2-40a3-8efb-2c6a739bdb03"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251202T043607Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b028c2c8-e0b6-45f4-aaa7-297d46a489f1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pramod@7kctech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260112T165745Z
