---
ID: "b262d9c4-931c-4d2c-97c3-4520097726aa"
Parent: "1f3e625a-558f-42cf-b4e9-92cc1e076eef"
Template: "1f3e625a-558f-42cf-b4e9-92cc1e076eef"
Path: /sitecore/templates/Project/Workwear/Page Content/Horizontal Teaser/Horizontal Teaser/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "eb6fc48d-2b42-4b5a-a4a4-9c0a61eeee11"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260102T121934Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6e288a47-ace8-40e5-86cc-62d619e092dd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\atanas@7kctech.com
    - ID: "bbaf3fad-8ffb-41e1-b8c4-5bcddcd2537e"
      Hint: ImageLeftPosition
      Value: 1
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260102T121950Z
